/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/428a03ec-1c3d-4bc2-9a86-b72f6b122ff8 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  int gas;
  bool enable;
  bool fire;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"
const int sBegin = 9600;
const int aWriteMax = 255;


void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  Serial.begin(sBegin);
  pinMode(13, INPUT);
  pinMode(2, INPUT); // Fire sensor input pin
  pinMode(3, OUTPUT); // Example PWM output pin
  pinMode(6, INPUT); // Ensure pin 5 is an input for the fire sensor
  analogWrite(3, aWriteMax); // Setting PWM on pin 3
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {

  // Your code here 
  
   ArduinoCloud.update();
  if (enable == true) {
     gas = analogRead(A1); // Read from analog pin A1
    Serial.print("Gas Level: ");
    Serial.println(gas);
    delay(100);
  
   fire = digitalRead(6); // Read digital value from pin 5
    Serial.print("Fire Sensor: ");
    Serial.println(fire);
    delay(100);
  }
}


/*
  Since Gas is READ_WRITE variable, onGasChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onGasChange()  {
  // Add your code here to act upon Gas change
}

/*
  Since Fire is READ_WRITE variable, onFireChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onFireChange()  {
  // Add your code here to act upon Fire change
}

/*
  Since Enable is READ_WRITE variable, onEnableChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onEnableChange()  {
  // Add your code here to act upon Enable change
}
